/**
 * Fast grensesnittstekst — skjemaetiketter, knapper og navigasjonshjelp.
 * Redaksjonell tekst hører hjemme i Sanity; dette er tekst som følger koden.
 * Legger du til en norsk streng, skal den engelske inn i samme slengen.
 */
export const UI = {
  no: {
    forside: {
      statusHytter: 'hytter',
      statusHytterLedige: 'ledige nå',
      statusTomter: 'tomter',
      statusTomterLedige: 'ledige nå',
      lesSaken: 'Les saken',
      ingenSaker: 'Ingen saker ennå.',
      ingenHytter: 'Ingen hytter å vise akkurat nå.',
    },
    tomter: {
      ledigeTomter: 'Ledige tomter',
      hvaDuKanBygge: 'Hva du kan bygge',
      ikkeTillatt: 'Ikke tillatt',
      ikkeTillattForklaring: 'Dette er ikke lov å bygge på tomta, etter reguleringsplanen.',
      levegg: 'Levegg',
      storrelse: 'Størrelse',
      maksByaToEtasjer: 'Maks BYA, to etasjer',
      maksByaTreEtasjer: 'Maks BYA, tre etasjer',
      maksGesimshoyde: 'Maks gesimshøyde',
      takform: 'Takform',
      maksBygningsbredde: 'Maks bygningsbredde',
      maksLengde: 'Maks lengde',
      moneretning: 'Møneretning',
      parkering: 'Parkering',
      toEtasjer: 'to etasjer',
      treEtasjer: 'tre etasjer',
      lastNedPlan: 'Last ned reguleringsbestemmelsene',
      planGrunnlag: 'Tallene er hentet fra',
      ringer: 'Ring',
      sendEpost: 'Send e-post',
    },
    omradet: {
      sommer: 'Sommer',
      vinter: 'Vinter',
      velgSesong: 'Velg sesong',
      sistOppdatert: 'Sist oppdatert',
      del: 'Del',
      lenkeKopiert: 'Lenke kopiert',
      alleSaker: 'Alle saker',
      ingenSaker: 'Ingen saker publisert ennå.',
      lesMer: 'Les saken',
    },
    hoppTilInnhold: 'Hopp til innhold',
    /** Henges bak tittelen på sider som lager tittelen sin fra data, som en hytte eller en modell. */
    tittelSuffiks: 'Nyørk Hemsedal',
    hjem: 'Hjem',
    hovedmeny: 'Hovedmeny',
    apneMeny: 'Åpne meny',
    byttSprak: 'English',
    velgSprak: 'Velg språk',
    velgTema: 'Velg lyst eller mørkt',
    temaLyst: 'Lyst',
    temaMorkt: 'Mørkt',
    navn: 'Navn',
    epost: 'E-post',
    telefon: 'Telefon',
    melding: 'Melding',
    valgfritt: 'valgfritt',
    jegVilHoreOm: 'Jeg vil gjerne høre om',
    personvern: 'Personvern',
    personvernFor: 'Vi behandler opplysningene etter',
    personvernLenke: 'personvernerklæringen',
    sender: 'Sender …',
    send: 'Meld interesse',
    honeypot: 'Ikke fyll ut dette feltet',
    hytter: {
      status: {ledig: 'Ledig', reservert: 'Reservert', solgt: 'Solgt'},
      statusEtikett: 'Status',
      byggetrinn: 'Byggetrinn',
      utenByggetrinn: 'Uten byggetrinn',
      situasjonsplan: 'Situasjonsplan',
      hyttetypene: 'Hyttetypene',
      ledigeHytter: 'Ledige hytter',
      alleHytter: 'Alle hytter',
      seHytta: 'Se hytta',
      seHyttetypen: 'Se hyttetypen',
      hytterAvDenneTypen: 'Hytter av denne typen',
      pris: 'Pris',
      prisPaForesporsel: 'Pris på forespørsel',
      hyttetype: 'Hyttetype',
      soverom: 'Soverom',
      bad: 'Bad',
      bra: 'BRA',
      prom: 'P-rom',
      etasjer: 'Etasjer',
      badstue: 'Badstue',
      vaskerom: 'Vaskerom',
      bod: 'Bod',
      terrasse: 'Terrasse',
      parkering: 'Parkering',
      tomt: 'Tomt',
      delomrade: 'Delområde',
      utsikt: 'Utsikt',
      solforhold: 'Solforhold',
      plantegninger: 'Plantegninger',
      fasadetegninger: 'Fasadetegninger',
      interior: 'Interiør',
      prospekt: 'Last ned prospekt',
      finn: 'Se annonsen på Finn',
      ja: 'Ja',
      alle: 'Alle',
      filtrer: 'Filtrer hyttene',
      nullstill: 'Nullstill',
      antallTreff: 'hytter vises',
      ingenTreff: 'Ingen hytter passer filteret. Prøv å fjerne et av valgene.',
      innholdKommer: 'Innholdet kommer.',
    },
  },
  en: {
    forside: {
      statusHytter: 'cabins',
      statusHytterLedige: 'available now',
      statusTomter: 'plots',
      statusTomterLedige: 'available now',
      lesSaken: 'Read more',
      ingenSaker: 'No news yet.',
      ingenHytter: 'No cabins to show right now.',
    },
    tomter: {
      ledigeTomter: 'Available plots',
      hvaDuKanBygge: 'What you can build',
      ikkeTillatt: 'Not permitted',
      ikkeTillattForklaring: 'The zoning plan does not allow these on the plot.',
      levegg: 'Privacy screen',
      storrelse: 'Size',
      maksByaToEtasjer: 'Max footprint, two storeys',
      maksByaTreEtasjer: 'Max footprint, three storeys',
      maksGesimshoyde: 'Max eaves height',
      takform: 'Roof',
      maksBygningsbredde: 'Max building width',
      maksLengde: 'Max length',
      moneretning: 'Ridge direction',
      parkering: 'Parking',
      toEtasjer: 'two storeys',
      treEtasjer: 'three storeys',
      lastNedPlan: 'Download the zoning rules',
      planGrunnlag: 'Figures are taken from',
      ringer: 'Call',
      sendEpost: 'Send email',
    },
    omradet: {
      sommer: 'Summer',
      vinter: 'Winter',
      velgSesong: 'Choose season',
      sistOppdatert: 'Last updated',
      del: 'Share',
      lenkeKopiert: 'Link copied',
      alleSaker: 'All news',
      ingenSaker: 'No news published yet.',
      lesMer: 'Read the story',
    },
    hoppTilInnhold: 'Skip to content',
    tittelSuffiks: 'Nyørk Hemsedal',
    hjem: 'Home',
    hovedmeny: 'Main menu',
    apneMeny: 'Open menu',
    byttSprak: 'Norsk',
    velgSprak: 'Choose language',
    velgTema: 'Choose light or dark',
    temaLyst: 'Light',
    temaMorkt: 'Dark',
    navn: 'Name',
    epost: 'Email',
    telefon: 'Phone',
    melding: 'Message',
    valgfritt: 'optional',
    jegVilHoreOm: "I'd like to hear about",
    personvern: 'Privacy',
    personvernFor: 'We handle your details according to our',
    personvernLenke: 'privacy policy',
    sender: 'Sending …',
    send: 'Register interest',
    honeypot: 'Do not fill in this field',
    hytter: {
      status: {ledig: 'Available', reservert: 'Reserved', solgt: 'Sold'},
      statusEtikett: 'Status',
      byggetrinn: 'Phase',
      utenByggetrinn: 'No phase set',
      situasjonsplan: 'Site plan',
      hyttetypene: 'The cabin types',
      ledigeHytter: 'Available cabins',
      alleHytter: 'All cabins',
      seHytta: 'View cabin',
      seHyttetypen: 'View cabin type',
      hytterAvDenneTypen: 'Cabins of this type',
      pris: 'Price',
      prisPaForesporsel: 'Price on request',
      hyttetype: 'Cabin type',
      soverom: 'Bedrooms',
      bad: 'Bathrooms',
      bra: 'Floor area',
      prom: 'Primary area',
      etasjer: 'Floors',
      badstue: 'Sauna',
      vaskerom: 'Utility room',
      bod: 'Storage',
      terrasse: 'Terrace',
      parkering: 'Parking',
      tomt: 'Plot',
      delomrade: 'Area',
      utsikt: 'View',
      solforhold: 'Sun',
      plantegninger: 'Floor plans',
      fasadetegninger: 'Elevations',
      interior: 'Interior',
      prospekt: 'Download prospectus',
      finn: 'View the listing on Finn',
      ja: 'Yes',
      alle: 'All',
      filtrer: 'Filter the cabins',
      nullstill: 'Reset',
      antallTreff: 'cabins shown',
      ingenTreff: 'No cabins match the filter. Try removing one of the choices.',
      innholdKommer: 'Content coming.',
    },
  },
} as const
